wormhole-foundation/relayer-engine

relayer-engine/src/executor/executorHarness.ts
relayer-engine/src/listener/listenerHarness.ts
relayer-engine/src/utils/providers.ts

If the plugin's handleWorkflow method throws, catch the error so that the process does not crash
Also guards against VAAs coming from spy that do not have sufficient signatures

Catch errors in handleWorkflow

---

relayer-engine/src/listener/eventHarness.ts
relayer-engine/src/listener/listenerHarness.ts
relayer-engine/src/listener/missedVaaFetching.ts
relayer-engine/src/listener/spyEventSource.ts

fixes #25 
testing:
- spawn listener
- send 1 message
- kill listener after message processed
- send 10 messages
- spawn listener
- observe that all 11 messages get processed
Importantly, no new vaa was needed to be found after the listener was spawned the second time for all vaas to be detected and refetched

Pessimistically fetch next vaa

---

relayer-engine/src/config/index.ts
relayer-engine/src/config/validateConfig.ts
relayer-engine/src/storage/dbConstants.ts
relayer-engine/src/storage/storage.ts

Add the ability to set a namespace for all the references used at Redis to avoid collisions when multiple relayers run over the same Redis instance.
see: https://github.com/wormhole-foundation/relayer-engine/issues/41

#41 - add namespace at redis storage

---

example-project/relayer-engine-config/common.json
relayer-engine/src/config/index.ts
relayer-engine/src/config/loadConfig.ts
relayer-engine/src/config/validateConfig.ts
relayer-engine/src/storage/redisStore.ts
relayer-engine/src/storage/storage.test.ts
relayer-engine/src/storage/storage.ts

In k8s we need to auth into redis and it's using TLS so we need to be able to pass in those env vars. Refactored redis config fields into a nested object and reading password from environment.

Adds configs to redis

---

relayer-engine/packages/relayer-plugin-interface/lib/index.d.ts
relayer-engine/packages/relayer-plugin-interface/src/index.ts
relayer-engine/src/storage/redisStore.ts
relayer-engine/src/storage/storage.ts

Discussion from slack
> Joe Howarth
:mountain:  [16 hours ago](https://teamillini.slack.com/archives/C04G11W5927/p1675901659985439)
[@gzimmermann](https://teamillini.slack.com/team/U04LXGVQF1R)
/ 
[@sscatularo](https://teamillini.slack.com/team/U04LLLJ4ENB)
could I get a review on this relayer engine pr? This is exposing some more paper cuts with transactionality and redis
https://github.com/wormhole-foundation/relayer-engine/pull/64
>Gabriel Zimmermann
:man-running:  [16 hours ago](https://teamillini.slack.com/archives/C04G11W5927/p1675901834249149?thread_ts=1675901659.985439&cid=C04G11W5927)
Just my ignorance but OpaqueTx is never; what does that mean? Hehe not familiar with the idiom
>Sebastián Nale
[15 hours ago](https://teamillini.slack.com/archives/C04G11W5927/p1675904993109669?threa …

Fix: allow nested calls to `withKeys` by passing tx object

---

relayer-engine/packages/relayer-plugin-interface/lib/index.d.ts
relayer-engine/packages/relayer-plugin-interface/src/index.ts
relayer-engine/src/executor/executorHarness.ts
relayer-engine/src/listener/missedVaaFetching.ts
relayer-engine/src/storage/redisStore.ts
relayer-engine/src/storage/storage.ts

Accomplishes 2 this:
1. Stores error information in redis when a workflow fails. To remove later: stacktrace. Once we have structured logging in place.
2. Added a catch for when fetching missing vaas fails so it doesn't interrupt the spy workflow.

Adds catching where it was missing and stores failed information for workflow in redis

---

relayer-engine/src/api/controller.ts
relayer-engine/src/storage/dbConstants.ts
relayer-engine/src/storage/index.ts
relayer-engine/src/storage/storage.test.ts
relayer-engine/src/storage/storage.ts

Sometimes it's useful to see the last completed workflows. Right now you have to scan the entire database to achieve that and inspect each workflow. It'd be nice to have them in a list however because the list can grow quite large I added a 100 element cap (in the future maybe you can make that configurable?)

Adds completed queue with a 100 elem cap

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/tracking_issue.md

closes #102
Update the issue templates on GitHub to standardize the way tasks are created for better readability.

Create/update issue templates on wormhole-foundation/relayer-engine repo

---

example-app/package-lock.json
example-app/package.json
example-app/src/app.ts
example-app/src/controller.ts
package-lock.json
relayer/application-standard.ts
relayer/application.ts
relayer/compose.middleware.ts
relayer/context.ts
relayer/index.ts
relayer/middleware/legacy-plugin/legacy-plugin.middleware.ts
relayer/middleware/metrics.middleware.ts
relayer/middleware/missedVaas.middleware.ts
relayer/middleware/source-tx.middleware.ts
relayer/middleware/tokenBridge.middleware.ts
relayer/storage/redis-storage.ts
relayer/storage/storage.ts
relayer/utils.ts

Motivation: To most integrators, this won't make a difference. They'll be using the `StandardRelayerApp` which hides everything behind the same interface. However, it opens the door to anybody that wants to leverage their own storage solution (SQS, Postgres, etc). And it's on them to then implement middleware that uses their same db if they want to avoid having to run multiple databases.
The change is to avoid locking people to redis, even if that's what we use and recommend using publicly. We will not provide an alternative storage backend for now.

Makes storage implementation swappable

---

relayer/application-standard.ts

If the user does not supply a logger in `opts` while creating a `StandardRelayerApp`, e.g.
```
const app = new StandardRelayerApp<MyRelayerContext>(env, opts);
```
Then VAA processing will fail due to the following error:
```
TypeError: Cannot read properties of undefined (reading 'child')
at /home/nsuri/example-sei-relayer/node_modules/@wormhole-foundation/relayer-engine/relayer/middleware/logger.middleware.ts:12:16
at callNext (/home/nsuri/example-sei-relayer/node_modules/@wormhole-foundation/relayer-engine/relayer/compose.middleware.ts:23:14)
at /home/nsuri/example-sei-relayer/node_modules/@wormhole-foundation/relayer-engine/relayer/compose.middleware.ts:25:12
at callNext (/home/nsuri/example-sei-relayer/node_modules/@wormhole-foundation/relayer-engine/relayer/compose.middleware.ts:23:1 …
```

Fix defaultOpts logger bug

---

relayer/application-standard.ts
relayer/middleware/wallet/wallet-management.ts
relayer/middleware/wallet/wallet.middleware.ts

Allows tokens to be passed to the wallet middleware so it can get metrics on specific tokens using the `tokens` param from WalletManager

Allow tokens to be passed as options

---

relayer/middleware/wallet/wallet.middleware.ts
relayer/middleware/wallet/walletToolBox.ts

We need access to `DirectSecp256k1HdWallet` instead of the `AccountData` so that in the `onSei` handler, the user can create a `signingCosmWasmClient`.

Fix SeiWallet to use DirectSecp256k1HdWallet instead of AccountData

---

package-lock.json
package.json
relayer/middleware/missedVaas/missedVaas.middleware.ts
relayer/utils.ts

New missedVaa implementation is throwing an error after been deployed.
The error is caused because the new implementation uses a new data-type to store the "seen" vaas, but the key used remains the same, which is causing a conflict when the missed VAA worker tries to fetch the "seen" vaas (it asks for a sorted set, but in redis there is a regular set for that key, which triggers an error at redis engine level).
Another possible solution would be to remove the prefix from redis at the moment of the deploy, but that would be something that any current user of the relayer engine would have to do, so it's not that easy to pull.
I've also added concurrency control to the missed vaa worker to avoid overloading redis with many concurrent queries

fix missedvaa prefix + limit  concurrency to crawl missing vaas

---

package-lock.json
package.json
relayer/middleware/missedVaas/missedVaas.middleware.ts
relayer/middleware/wallet/wallet-management.ts

TODO: the spy pushes the same vaa multiple times (a consequence of its stateless nature coupled with a p2p network natural behavior). We shouldn't hit redis needlessly if we've already seen a vaa.

Adds listener for skipped vaas

---

relayer/middleware/source-tx.middleware.ts

In the fetch function:
- Adds HTTP body response to some errors if present (still assumes it is UTF8 encoded)
- Throws error on anything outside the 200-299 HTTP response status range.

relayer: improves error messages in source tx middleware.

---

README.md
advanced-example.md
example-app/README.md
example-app/package-lock.json
example-app/package.json
example-app/src/app.ts

I'd like to use these markdown files directly in the docs, so the readme is wordsmithed a bit and a there is a new markdown file to explain the `example-app`.
------
Is anything missing?
Notably there is no detail on what to do inside the callback once a VAA is received. Almost always a dev would want to see some example of how the VAA is actually relayed/redeemed, not just fetched and persisted.
Should I wait on the `connect-sdk` to be released or try to write something using the existing SDK?

Docs: reformat readme to be more like a tutorial

---

relayer/middleware/providers.middleware.ts

On monday we started getting errors with status-code 526, of the like:
They were caused by the default sei provider declared on the RE having an expired SSL certificate.
To debug this, I noticed that the error stack is lost and the error logged is not very useful, so this PR:
- Adds the stack correct stack trace to the error
- Logs a friendlier message
Also, something that made this difficult to debug, is that our relayer isn't really using SEI, so I didn't expect to see an error on the Sei provider.
This is because providers are started for all chains supported by the RE, instead of the actual chains in use by the RE.
This PR addresses this issue by adding a second, optional (to avoid a breaking change), parameter that allows to configure what chains are used by the relayer.

Hotfix: provider middleware

---

.github/workflows/test.yaml
example-app/src/app.ts
example-app/src/log.ts
relayer/application-standard.ts
relayer/bundle-fetcher.helper.ts
relayer/storage/redis-storage.ts
relayer/utils.ts

Adds a custom exponential backoff with threshold strategy. Although bullmq supports exponential backoff, it does not allow stopping the continuously increasing delay.
In this implementation, `baseDelayMs` will be increased exponentially on each retry attempt, until it reaches `maxDelayMs`, which will be the constant delay applied onwards.

[Feature] Add custom exponential backoff strategy with threshold

---

relayer/context.ts
relayer/middleware/metrics.middleware.ts
relayer/storage/storage.ts
test/middleware/metrics.middleware.test.ts
tsconfig.json

Enhances current metric middleware with the following features:
- expose processing duration (both success and failures via labeling)
- expose total duration
- add labels customization based on context
- add terminal label on vaas_finished_total
Usage example:
``` import { MetricLabelsOpts, MetricsOpts, metrics } from "@wormhole-foundation/relayer-engine";
import { Context } from "../app";
import { Registry } from "prom-client";
import { ChainId, coalesceChainName } from "@certusone/wormhole-sdk";
const metricsOpts = (registry: Registry): MetricsOpts<Context> => {
function labelsCustomizer(ctx: Context): Promise<Record<string, string | number>> {
const chainId = ctx.executionRecord.deliveryRecord.chainId as ChainId;
return Promise.resolve({
targetChain: coalesceChainName(chainId)
});
} …
```

Add processing duration metric + customization

---

relayer/middleware/providers.middleware.ts

Adds a small functionality to mask sensitive Blockdaemon RPC urls from being logged.
Tested the snippet separately passing data, works well.

Mask BlockDaemon RPC endpoints in logs

---

package.json

both prepare and prepack run after installing from a gitrepository AND before packing a tarball for publishing. This means we can run typescript -> js compilation here.

Use prepack instead of prepare for yarn compat

---

package.json

This reverts commit 80e232e3ab0fb34cce681d2c2b5656e68464d5a2.
Some integrators reported having their build pipeline broke by the change. Currently I don't have capacity to find a solution that works both for yarn and npm, so I'm resorting to reverting the change. Do we have reasons to believe reverting this change might break some other integrators code?

Revert "Use prepack instead of prepare for yarn compat (#169)"

---

relayer/middleware/missedVaasV3/check.ts
relayer/middleware/missedVaasV3/helpers.ts
relayer/middleware/missedVaasV3/worker.ts
test/middleware/missedVaasV3/check.test.ts

Currently, the behavior is that when it looks ahead it stops after the first failure assuming that it is up-to-date with VAAs published. The problem with this approach is that sometimes the Guarding misses some VAAs, i.e: sequences: [210 - 211 - 212 - 213 (not available in the guardian) - 214...]. In this example, the look-ahead function will continue until 213, it'll fail to fetch it, so it will stop there but we have more VAAs that could be retrieved.
This new approach uses a MAX_LOOK_AHEAD constant so it will continue fetching VAAs until the failures count reaches the MAX_LOOK_AHEAD value set previously, only then it will consider there are no more VAAs available to retrieve.

Add max look-ahead capability

---

package-lock.json
package.json

Latest `wormhole-sdk` is 0.10.11, this will also need to be published to NPM (latest version for this package npm is still on 0.9.24)

Deps: Bump certusone sdk dependency to latest

---

README.md
examples/advanced/package.json
examples/simple/package.json
package.json
relayer/application.ts

guardian: update xlabs testnet guardians
We are deprecating `nodes.stable.io` domains and created a new domains for guardian testnet instances.

guardian: update xlabs testnet guardians
